refactor ('install' action): add inputs.accept-license that must be explicitly set to 'YES' by calling job/action (refactor/install-action) [#224]
- **refactor ('install' action): add description**
- **refactor ('install' action): add inputs.accept-license that must be explicitly set to 'YES' by calling job/action**
- **refactor ('install' action): replace automatic agreeing to license with check on inputs.accept-license value**
- **refactor ('nugettier-publish-package' action): set install.accept-license explicitly to 'YES'**
- **refactor ('build-pr' workflow): set install.accept-license explicitly to 'YES'**
- **refactor ('publish' workflow): set install.accept-license explicitly to 'YES'**

diff --git a/.github/actions/install/action.yml b/.github/actions/install/action.yml
--- a/.github/actions/install/action.yml
+++ b/.github/actions/install/action.yml
@@ -1,14 +1,37 @@
 name: Install NuGettier
+description: >-
+  GitHub Action to install NuGettier
+
+inputs:
+  accept-license:
+    description: "[YES|NO] Must be set explicitly to 'YES' to accept the license. Install won't proceed without."
+    required: false
+    default: NO
+
+
 runs:
   using: composite
   steps:
   - name: Display license
     shell: bash
     run: |-
-      echo "By running this installation script"
-      echo "you automatically agree to the license terms of this Software Product"
-      echo ""
       curl -s https://raw.githubusercontent.com/KageKirin/NuGettier/main/LICENSE
+
+  - name: Check license acceptation
+    shell: bash
+    run: |-
+      accept=${{ inputs.accept-license }}
+      if [ "${accept,,}" == "yes" ]; then
+        echo "Thank you for accepting the license terms."
+        echo "Installation can proceed."
+        exit 0
+      else
+        echo "Sorry, but you have to explicitly accept the license terms"
+        echo "by setting accept-license to 'yes'."
+        echo "Installation cannot proceed"
+        exit 1
+      fi
+
   - name: Install
     shell: bash
     run: |-
